contentType: post
id: examplepost
priority: 6
description: An example post
content:
  slug:
    en-US: mgnc-a-serverless-blog-at-no-cost
  title:
    en-US: MGNC
  excerpt:
    en-US: A serverless, continous delivery first, near to 0$ costs, extensible micro CMS generating static contents
  content:
    en-US: Place your content here!
  author:
    en-US:
      sys:
        type: Link
        linkType: Entry
        id: brossi
  tags:
    en-US:
      - sys:
          type: Link
          linkType: Entry
          id: devops
