contentType: option
id: metadata
priority: 2
description: The metadata option
content:
  name:
    en-US: metadata
  value:
    en-US:
      theme:
        name: Attila
        description: A free theme for the Ghost web blog platform
        url: https://github.com/zutrinken/attila
        credits:
          - url: https://github.com/zutrinken
            name: Peter Amende
        dir: '{themeDir}'
      webSite:
        title: NGMC
        description: A serverless, continous delivery first, near to 0$ costs, extensible micro CMS generating static contents
        keywords: Netlify, Github, Metalsmith, Contentful, Serverless, Continous Delivery, 0$
        author: Bruno Rossi <brunorossiweb@gmail.com>
        url: http://ngmc.netlify.com
        favIcon: ''
        logoUrl: ''
        showMenuButton: true
        styles:
          bodyClass: ''
        platform:
          name: NGMC
          url: https://github.com/brunorossi/ngmc
        header:
          coverImageUrl: ''
          title: ''
      googleAnalytics:
        code: ''
      openGraph:
        type: website
        title: NGMC
        siteName: NGMC
        description: A serverless, continous delivery first, near to 0$ costs, extensible micro CMS generating static contents
        url: http://ngmc.netlify.com
        image: ''
      twitter:
        card: summary
        title: NGMC
        description: A serverless, continous delivery first, near to 0$ costs, extensible micro CMS generating static contents
        image: ''
